# -*- coding: utf-8 -*-
"""Tensors.ipynb

Automatically generated by Colab.
"""

import torch
print(torch.__version__)

if torch.cuda.is_available():
  print("GPU is available")
  print(f'Using GPU: {torch.cuda.get_device_name(0)}')
else:
  print("GPU not available. Using CPU.")

"""### **Creating Tensors**"""

# Using empty
torch.empty(2,3)

# Using zeroes
p = torch.zeros(3,2)
print(p)

# Check type
print(p.dtype)

# Using ones
torch.ones(2,3)

# Using rand
torch.rand(2,3)                                           # rand will give float values 0 to 1

# Use of seed
b = torch.rand(2,3)                                          # got different values than above

# Use of manual_seed
torch.manual_seed(100)                                      #It ensure that the "random" numbers generated are exactly the same every time the code is executed.
torch.rand(3,3)

# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

# Other ways

# Using arange
print("Using arange:", torch.arange(2, 9, 2))

# Using linspace[Linearly Spaced]
print("Using linspace:", torch.linspace(0,10,10))

# Using eye [Identity:- 2X2 mptrix]
print("Using eye:", torch.eye(4))

# Using full
print("Using full:", torch.full((3,3), 5))

"""### Tensor Shapes"""

x = torch.tensor([[1,2,3], [4,5,6]])
x

x.shape

x.reshape(3, 2)

torch.empty_like(x)                                                                           # Creating tensor of same shape ps x

torch.ones_like(x)

torch.zeros_like(x)

torch.rand_like(x, dtype=torch.float)

"""### **Tensor Data Types**"""

# Finding data type
x.dtype

# assigning data type
torch.tensor([1.0,2.0,3.0], dtype=torch.float32)

# Using to()
x.to(torch.float32)                                                                         #will convert existing dtype to other dtype

"""### **Mathematical Operations**

#### **1. Scalar Operation**
"""

x = torch.rand(3,3)
x

# addition
x + 1

# Substraction
x - 1

# Multiplication
x * 2

# Division
x / 2

# Int Division
(x*100)//2

# Mod
x % 2

# Power
x ** 2

"""#### **2. Element wise Operation**"""

p = torch.rand(2,3)
q = torch.rand(2,3)
print(p)
print(q)

## add
p + q
# sub
p - q
# multiply
p * q
# division
p / q
# power
p ** q
# mod
p % q

r = torch.tensor([1,-2,3,-4])

# abs
torch.abs(r)

# negative
torch.neg(r)

s = torch.tensor([1.0, 2.2, 3.5, 4.4])

# round
torch.round(s)

# ceil
torch.ceil(s)

# floor
torch.floor(s)

# clamp
torch.clamp(s, min=2, max=3)

"""#### **3. Reduction Operation**"""

e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

# median
torch.median(e)

# max and min
torch.max(e)
torch.min(e)

# product
torch.prod(e)

# standard deviation
torch.std(e)

# variance
torch.var(e)

# argmax
torch.argmax(e)

# argmin
torch.argmin(e)

"""#### **4. Matrix Operations**"""

f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

# Matrix Multiplication
torch.matmul(f, g)

vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

#Dot product
torch.dot(vector1, vector2)

# Transpose
torch.transpose(f, 0, 1)

h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

# Determinent
torch.det(h)

# Inverse
torch.inverse(h)

"""#### **5. Comparison Operations**"""

i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

"""#### **6. Special Functions**"""

k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

# Log
torch.log(k)

# Exponents
torch.exp(k)

# Square Root
torch.sqrt(k)

# Sigmoid
torch.sigmoid(k)

"""ReLU and Softmax are two of the most popular activation functions. ReLU is used in the hidden layers to help the network learn complex patterns, while Softmax is used at the very end (output layer) to turn raw numbers into probabilities for classification."""

# Softmax
torch.softmax(k, dim=0)

# Relu
torch.relu(k)

"""### **Inplace Operations**"""

m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

m.add_(n)

m

n

torch.relu(m)

m.relu_()

m

"""### **Copying a Tensor**"""

a = torch.rand(2,3)
a

# Copying tensor 'a' here to 'b'
b = a

b

a[0][0] = 0

a

b          # here b also affects if there's any change in 'a'

id(a)

id(b)

# Copying 'a' using clone()
b = a.clone()

a

b

a[0][0] = 10

a

b

id(a)

id(b)
